version: '3'

services: 
    product-service:
        build: ./products
        volumes: 
            - ./products:/usr/src/app
        ports:
            - 5002:80

    website:
        image: php:apache
        volumes: 
            - ./webserver:/var/www/html
        ports:
            - 5000:80
        depends_on: 
            - product-service